"use client";
import React, { useState } from "react";
import * as XLSX from "xlsx";
import { Alert, Button, Input, Modal, Table, Tag, Upload, message } from "antd";
import { CheckCircleOutlined, EditOutlined, InboxOutlined, WarningOutlined } from "@ant-design/icons";
import { useConfirmCourierCodSettlementMutation, usePreviewCourierCodSettlementMutation } from "@/redux/api/orderApi";
const get=(r:any,k:string)=>r[k]??r[k.toLowerCase()]??r[k.replaceAll(" ","_")]; const tk=(v:any)=>`Tk ${Number(v||0).toLocaleString()}`; const num=(v:any)=>{const n=Number(String(v??"").replace(/[,৳\s]/g,""));return Number.isFinite(n)?n:NaN};
export default function CourierCodExcelReconciliation(){
 const [open,setOpen]=useState(false),[rows,setRows]=useState<any[]>([]),[preview,setPreview]=useState<any[]>([]),[selected,setSelected]=useState<React.Key[]>([]),[target,setTarget]=useState<any>(null),[reason,setReason]=useState("");
 const [previewApi,{isLoading:previewing}]=usePreviewCourierCodSettlementMutation(),[confirmApi,{isLoading:confirming}]=useConfirmCourierCodSettlementMutation();
 const reset=()=>{setRows([]);setPreview([]);setSelected([]);setTarget(null);setReason("")};
 const reload=async(input:any[])=>{const r:any=await previewApi(input).unwrap(),d=r.data||[];setPreview(d);setSelected(d.filter((x:any)=>x.matched).map((x:any)=>x.rowIndex));return d};
 const upload=async(file:File)=>{try{const wb=XLSX.read(await file.arrayBuffer(),{type:"array"});const raw=XLSX.utils.sheet_to_json<any>(wb.Sheets[wb.SheetNames[0]],{defval:""});const data=raw.map(x=>({invoice:String(get(x,"Invoice")||"").trim(),trackingCode:String(get(x,"Tracking Code")||"").trim(),codAmount:num(get(x,"COD Amount")),shippingCharge:get(x,"Shipping Charge")===""?null:num(get(x,"Shipping Charge")),deliveryStatus:String(get(x,"Delivery Status")||"").trim()}));if(!data.length)throw new Error("The first worksheet has no rows");setRows(data);const d=await reload(data);message.success(`${d.filter((x:any)=>x.matched).length} row(s) ready. No data changed yet.`)}catch(e:any){reset();message.error(e?.data?.message||e.message||"Could not read Excel")}return false};
 const apply=async()=>{if(!target||reason.trim().length<5)return message.warning("A clear discount reason is required");const changed=rows.map((x,i)=>i===target.rowIndex?{...x,adjustmentType:"Customer Negotiated Discount",adjustmentReason:reason.trim()}:x);try{await reload(changed);setRows(changed);setTarget(null);message.success("Discount applied to preview. Confirm settlement to save it.")}catch(e:any){message.error(e?.data?.message||"Could not apply adjustment")}};
 const confirm=async()=>{const chosen=preview.filter(x=>selected.includes(x.rowIndex));if(!chosen.length)return message.warning("Select at least one ready row");try{await confirmApi(chosen.map(x=>rows[x.rowIndex])).unwrap();message.success(`${chosen.length} settlement row(s) completed.`);setOpen(false);reset()}catch(e:any){message.error(e?.data?.message||"Nothing changed. Refresh and review again.")}};
const review=(r:any)=>Modal.info({title:`Review ${r.invoice}`,content:<div><p><b>Courier COD:</b> {tk(r.codAmount)}</p><p><b>ERP unpaid balance:</b> {tk(r.order?.expectedCod)}</p><p><b>Difference:</b> {tk(Math.abs(Number(r.difference||0)))}</p><Alert type={r.difference<0?"error":"warning"} showIcon message={r.difference<0?"Over-collection: do not settle this row":"Under-collection"} description={r.difference<0?"Courier amount is higher than ERP balance. Check the Excel invoice/COD or make an authorised order correction. It cannot be auto-settled.":"Use approved discount only when the customer agreed to the lower final price."}/><p className="mt-3 text-xs">System reason: {(r.reasons||[]).join("; ")}</p></div>,okText:"Close"});
 const cols:any=[{title:"Invoice",dataIndex:"invoice",render:(v:string)=><b>{v||"-"}</b>},{title:"Tracking",dataIndex:"trackingCode",render:(v:string)=>v||"Not available"},{title:"Courier COD",dataIndex:"codAmount",render:tk},{title:"ERP expected",render:(_:any,r:any)=>r.order?<><b>{tk(r.order.expectedCod)}</b>{r.difference>0&&<div className="text-xs text-rose-600">Short: {tk(r.difference)}</div>}{r.difference<0&&<div className="text-xs text-rose-600">Extra: {tk(Math.abs(r.difference))}</div>}</>:"-"},{title:"Status / action",width:300,render:(_:any,r:any)=>r.matched?<><Tag icon={<CheckCircleOutlined/>} color={r.adjustmentAmount?"gold":"green"}>{r.adjustmentAmount?`Adjusted: discount ${tk(r.adjustmentAmount)}`:"Matched - ready"}</Tag>{r.adjustmentReason&&<p className="mb-0 mt-1 text-xs text-amber-700">Reason: {r.adjustmentReason}</p>}</>:r.alreadyReconciled?<><Tag color="blue">Already settled</Tag><p className="mb-0 mt-1 text-xs text-blue-600">Already in Payment History. Duplicate is blocked.</p></>:<><Tag icon={<WarningOutlined/>} color="red">Needs review</Tag><p className="mb-1 mt-1 text-xs text-rose-600">{r.reasons.join("; ")}</p><Button size="small" onClick={()=>review(r)}>Review row</Button>{Number(r.order?.expectedCod||0)>Number(r.codAmount||0)&&<Button size="small" className="ml-2" icon={<EditOutlined/>} onClick={()=>{setTarget(r);setReason("")}}>Discount</Button>}</>}];
 const exact=preview.filter(r=>r.matched&&!r.adjustmentAmount).length,adjusted=preview.filter(r=>r.matched&&r.adjustmentAmount).length,unresolved=preview.filter(r=>!r.matched&&!r.alreadyReconciled).length;
 return <><Button icon={<InboxOutlined/>} onClick={()=>setOpen(true)}>Import COD Excel</Button><Modal open={open} onCancel={()=>{setOpen(false);reset()}} width={1200} title="Courier COD Excel Reconciliation" footer={preview.length?[<Button key="cancel" onClick={()=>{setOpen(false);reset()}}>Cancel</Button>,<Button key="confirm" type="primary" disabled={!selected.length} loading={confirming} onClick={confirm}>Confirm selected settlements ({selected.length})</Button>]:null} destroyOnClose>{!preview.length?<><Alert className="mb-4" type="info" showIcon message="Upload creates preview only" description="No order, payment or discount changes before final confirmation."/><Upload.Dragger accept=".xlsx,.xls" maxCount={1} beforeUpload={upload} showUploadList={false} disabled={previewing}><p className="ant-upload-drag-icon"><InboxOutlined/></p><p className="ant-upload-text">Drop courier payment Excel here</p><p className="ant-upload-hint">Invoice, Tracking Code, COD Amount and Shipping Charge.</p></Upload.Dragger></>:<><div className="mb-4 grid grid-cols-3 gap-3"><div className="rounded border border-emerald-200 bg-emerald-50 p-3"><b className="text-lg text-emerald-700">{exact}</b><div className="text-xs">Exact matched</div></div><div className="rounded border border-amber-200 bg-amber-50 p-3"><b className="text-lg text-amber-700">{adjusted}</b><div className="text-xs">Approved discount</div></div><div className="rounded border border-rose-200 bg-rose-50 p-3"><b className="text-lg text-rose-700">{unresolved}</b><div className="text-xs">Needs action</div></div></div><Alert className="mb-4" type="warning" showIcon message="Review before confirmation" description="Only green/approved-discount rows are selectable; the server re-checks all values."/><Table rowKey="rowIndex" size="small" scroll={{x:1000,y:440}} dataSource={preview} columns={cols} pagination={{pageSize:25}} rowSelection={{selectedRowKeys:selected,onChange:setSelected,getCheckboxProps:(r:any)=>({disabled:!r.matched})}}/></>}<Modal open={Boolean(target)} title="Approve customer negotiated discount" onCancel={()=>setTarget(null)} onOk={apply} okText="Apply to preview" destroyOnClose><Alert className="mb-4" type="warning" showIcon message={`Received ${tk(target?.codAmount)}; expected ${tk(target?.order?.expectedCod)}`} description={`Difference ${tk(Math.max(0,Number(target?.order?.expectedCod||0)-Number(target?.codAmount||0)))} will become discount only after final confirmation.`}/><label className="mb-2 block text-sm font-medium">Approval reason *</label><Input.TextArea rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Example: Customer agreed final price after phone confirmation"/></Modal></Modal></>;
}
