export enum tagTypes {
      mainCategory="mainCategory",
      vendor="vendor",
      brand="brand",
      products="products",
      order="order",
      division="division",
      auth="auth",
      delivery="delivery",
      users="users",
      office="office",
      department="department",
      requisition="requisition",
      userPermission="userPermission",
      customer="customer",
      inventory="inventory",
      warehouse="warehouse",
      status="status",
      comment="comment",
      supplier="supplier",
      procurements="procurements",

  }
  
  export const tagTypesList = [
    tagTypes.mainCategory,
    tagTypes.vendor,
    tagTypes.brand,
    tagTypes.products,
    tagTypes.order,
    tagTypes.auth,
    tagTypes.delivery,
    tagTypes.division,
    tagTypes.users,
    tagTypes.office,
    tagTypes.department,
    tagTypes.requisition,
    tagTypes.userPermission,
    tagTypes.customer,
    tagTypes.inventory,
    tagTypes.warehouse,
    tagTypes.status,
    tagTypes.comment,
    tagTypes.supplier,
    tagTypes.procurements,
  ];