"use client";
import { Button, Card, Form, Input, InputNumber, Modal, Table, message } from "antd";
import { useState } from "react";
import GbHeader from "@/components/ui/dashboard/GbHeader";
import { useCreateOfficeMutation, useGetOfficesQuery, useUpdateOfficeMutation } from "@/redux/api/hrPayrollApi";

export default function OfficesPage() {
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<any>(null); const [form] = Form.useForm();
  const latitude = Form.useWatch("latitude", form); const longitude = Form.useWatch("longitude", form); const radius = Form.useWatch("radiusMeters", form) || 100;
  const { data, isLoading } = useGetOfficesQuery(undefined); const [createOffice, { isLoading: creating }] = useCreateOfficeMutation(); const [updateOffice, { isLoading: updating }] = useUpdateOfficeMutation();
  const save = async (values: any) => { try { if (editing) await updateOffice({ id: editing.id, ...values }).unwrap(); else await createOffice(values).unwrap(); message.success(editing ? "Office geofence updated" : "Office geofence created"); form.resetFields(); setEditing(null); setOpen(false); } catch (e: any) { message.error(e?.data?.message || "Could not save office"); } };
  const showEditor = (office?: any) => { setEditing(office || null); form.setFieldsValue(office || { radiusMeters: 100 }); setOpen(true); };
  const hasLocation = Number.isFinite(Number(latitude)) && Number.isFinite(Number(longitude));
  const circleSize = Math.min(180, Math.max(58, Math.sqrt(Number(radius || 100)) * 8));
  return <div className="p-6 space-y-6"><GbHeader title="Office & Attendance Range" /><Card title="Office Geofences" extra={<Button type="primary" onClick={() => showEditor()}>Add Office</Button>}><p className="text-gray-500 mb-4">Employees can manually check in/out only when their browser location is inside one of these office ranges.</p><Table loading={isLoading} dataSource={data?.data || []} rowKey="id" columns={[{ title: "Office", dataIndex: "name" }, { title: "Address", dataIndex: "address" }, { title: "Latitude", dataIndex: "latitude" }, { title: "Longitude", dataIndex: "longitude" }, { title: "Allowed Range", dataIndex: "radiusMeters", render: (v) => `${v} meters` }, { title: "Action", render: (_: any, row: any) => <Button type="link" onClick={() => showEditor(row)}>Edit</Button> }]} /></Card><Modal open={open} title={editing ? "Edit Office Geofence" : "Add Office Geofence"} footer={null} onCancel={() => { setOpen(false); setEditing(null); }}><Form form={form} layout="vertical" onFinish={save}><Form.Item name="name" label="Office Name" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="address" label="Address"><Input /></Form.Item><Form.Item name="latitude" label="Map Latitude" rules={[{ required: true }]}><InputNumber className="w-full" precision={7} /></Form.Item><Form.Item name="longitude" label="Map Longitude" rules={[{ required: true }]}><InputNumber className="w-full" precision={7} /></Form.Item><Form.Item name="radiusMeters" label="Allowed Radius (meters)" rules={[{ required: true }]}><InputNumber className="w-full" min={10} /></Form.Item>{hasLocation && <div className="relative h-56 overflow-hidden rounded-xl border mb-5"><iframe title="Office geofence map" className="w-full h-full border-0" src={`https://www.openstreetmap.org/export/embed.html?bbox=${Number(longitude)-0.004}%2C${Number(latitude)-0.003}%2C${Number(longitude)+0.004}%2C${Number(latitude)+0.003}&layer=mapnik&marker=${latitude}%2C${longitude}`} /><div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-blue-600 bg-blue-500/20 pointer-events-none flex items-center justify-center" style={{ width: circleSize, height: circleSize }}><span className="bg-white/90 text-xs font-bold px-2 py-1 rounded-full text-blue-700">{radius} m</span></div></div>}<Button htmlType="submit" type="primary" loading={creating || updating}>Save Office Range</Button></Form></Modal></div>;
}
